@startuml
sprite $AndGate [49x73/16z] {
xT45ZY0n34HHEowxxAps_iSTXcOIZ_A43JyeswpaEYDP_vCCbNCQ_uhXxo9xuNJm8c3uO8R8z7OqEea59rrsj2GsUCRUmH2RFAcoPkdOmrmNMc7OjLwL9d4a
VH44SSYpoLIZ6mxH3oOudqBJSOOn2L0uOzvdApASwcro1uvpvEII3HVKyy1vBT2xGLiSqfaSmTm8HZ224OnW12FOByqcGSKLzHCOVtGkzEItK5dHrCKBcYmS
1yBs1uDN
}
sprite $OrGate [48x66/16z] {
xPPNegGm40F1Laiozx_lPZ9DsFHYJVWgTvm1kaCGNSBB-C7-YTwhyO5UhP3hNHsD5M33BRlOWU-4xpHHJOn8vJAwX1cfl-mKItX-e9XOGv-LP64BdMUWiKUH
pnq7X6jMV5GSaBKWuHWTxYsC32CPPG9r45x0WmIzY1nwwyCueyKcV59zjcKOvmWhFmcVZQWQ5uHBCim4CHbcGgXFohdU6LtnfA366pvdVmZWGGF5kEMNP9e9
gcExlEUF0zA_yVbd_gV_wN_w4QH6616fNn6KsY0oVaBAWyL0FV1f4MNp15DRW3OtVWMRuxj9RkvJvTjNk77bq-D3mix_cGusDVbDtwAa_a-gXnYTkURSxyeK
VxOpFuTwvfVIhQZTV-Oh
}
@enduml
